[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API proxy to avoid CORS issues during development
[[redirects]]
  from = "/api/*"
  to = "https://api.capitalcue.com/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.capitalcue.com"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Environment-specific redirects for staging
[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_DOCUMENT_API = "https://staging-api.capitalcue.com/documents"
    VITE_CONSTRAINT_API = "https://staging-api.capitalcue.com/constraints"
    VITE_ALERTS_API = "https://staging-api.capitalcue.com/alerts"
    VITE_AI_API = "https://staging-api.capitalcue.com/ai"