apiVersion: v1
kind: ConfigMap
metadata:
  name: financial-analyzer-config
  namespace: financial-analyzer
data:
  # Application Configuration
  NODE_ENV: "production"
  API_PORT: "3001"
  WEB_PORT: "3000"
  LOG_LEVEL: "info"
  
  # Database Configuration
  DATABASE_NAME: "financial_analyzer"
  DATABASE_USER: "postgres"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # MCP Services Configuration
  MCP_DOCUMENT_PARSER_URL: "http://document-parser-service:8001"
  MCP_CONSTRAINT_ENGINE_URL: "http://constraint-engine-service:8002"
  MCP_ALERT_MANAGER_URL: "http://alert-manager-service:8003"
  MCP_AI_ANALYZER_URL: "http://ai-analyzer-service:8004"
  
  # File Upload Configuration
  UPLOAD_DIR: "/app/uploads"
  MAX_FILE_SIZE: "52428800"

---
apiVersion: v1
kind: Secret
metadata:
  name: financial-analyzer-secrets
  namespace: financial-analyzer
type: Opaque
data:
  # Base64 encoded secrets (update these with actual values)
  DATABASE_PASSWORD: cG9zdGdyZXM=  # 'postgres' - change this!
  REDIS_PASSWORD: cmVkaXMxMjM=      # 'redis123' - change this!
  JWT_SECRET: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXktaGVyZQ==  # change this!
  ANTHROPIC_API_KEY: eW91ci1hbnRocm9waWMtYXBpLWtleS1oZXJl  # change this!